name: METAR Auto Update

on:
  schedule:
    - cron: "4,9,17,22,37,48 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show UTC Time
        run: date -u

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run METAR Engine
        env:
          FONNTE_TOKEN: ${{ secrets.FONNTE_TOKEN }}
        run: python metar_engine.py

      - name: Commit & Push if Changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add metar_history.csv

          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto update METAR"
            git push
          fi
